# *ASSIGNMENT 1 NUMPY*

# Q1) Create a null vector of size 10 but the fifth value which is 1.

In [ ]:
import numpy as np
x = np.zeros(10)
print(x)
print("fifth value is 1")
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
fifth value is 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


# Q2) Create a vector with values ranging from 10 to 49.

In [ ]:
import numpy as np
v = np.arange(10,49)
print("Given vector:")
print(v)
print("Resultant vector")
v[1:-1]
print(v)

Given vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Resultant vector
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Q3) Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Q4) Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
import numpy as np
a = np.array([1,2,0,0,4,0])
print("Given array:")
print(a)
print("Indices of non-zero elements:")
result = np.where(a != 0)[0]
print(result)

Given array:
[1 2 0 0 4 0]
Indices of non-zero elements:
[0 1 4]


# Q5) Create a 10x10 array with random values and find the minimum and maximum values.


In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Given array:")
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Given array:
[[0.71786932 0.19520924 0.83896499 0.50289807 0.10190611 0.95202651
  0.26288351 0.65897647 0.77903395 0.79874889]
 [0.08130577 0.15618941 0.01475821 0.11873993 0.96372306 0.46770418
  0.57621838 0.34924573 0.10544634 0.96852439]
 [0.25225476 0.63888997 0.46092451 0.92300582 0.7646733  0.00945409
  0.62264913 0.05059678 0.03929008 0.46336738]
 [0.34796536 0.46382149 0.87925794 0.84197478 0.71783585 0.62251025
  0.03285585 0.70125083 0.79541208 0.02354841]
 [0.92080238 0.12514662 0.04926977 0.92267327 0.34858589 0.68702519
  0.89366659 0.25442766 0.4023414  0.5117142 ]
 [0.45862278 0.10476896 0.32359154 0.74941328 0.32553181 0.13574541
  0.24214529 0.75580086 0.24003749 0.02107233]
 [0.34331497 0.75425724 0.1360388  0.3746934  0.06127822 0.50965138
  0.13680423 0.3672662  0.84109943 0.7382253 ]
 [0.95033291 0.68932309 0.60592751 0.73977935 0.08782954 0.82980841
  0.37490842 0.92920052 0.5086886  0.26482683]
 [0.25188579 0.6358603  0.0236245  0.93920288 0.0526337  0.70138571

# Q6) Create a random vector of size 30 and find the mean value.

In [ ]:
import numpy as np
x = np.random.random(30)
print("Given array:")
print(x)
m = x.mean()
print("Mean value:")
print(m)

Given array:
[0.32199659 0.05294068 0.69442311 0.72166496 0.69027733 0.55591819
 0.55434365 0.51810722 0.20736984 0.44826227 0.31502681 0.94870226
 0.35089336 0.09088188 0.64343073 0.83371887 0.21370284 0.75933691
 0.33468384 0.33670276 0.00959953 0.7825167  0.31817195 0.12332002
 0.83906297 0.13764526 0.80785197 0.6477828  0.45176494 0.58518068]
Mean value:
0.47650936323499676
